FROM node:20-alpine

WORKDIR /app

RUN corepack enable

COPY package.json pnpm-lock.yaml ./
RUN pnpm install

COPY prisma ./prisma
COPY prisma.config.ts ./

RUN pnpm prisma generate

EXPOSE 8000

CMD ["pnpm", "dev"]